language: node_js

before_install:
- npm install -g npm@5
- npm install -g greenkeeper-lockfile@1
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
- chmod +x ./cc-test-reporter

before_script:
- greenkeeper-lockfile-update
- ./cc-test-reporter before-build

after_script:
- greenkeeper-lockfile-upload
- ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

script:
- npm run qa

jobs:
  include:
  - stage: npm Deployment
    deploy:
      edge: true
      provider: npm
      skip_cleanup: true
      email: "$NPM_EMAIL"
      api_key: "$NPM_TOKEN"
      on:
        tags: true

node_js:
- "8"
- "10"
- "12"
- "13"
